GET http://localhost:3000/api/cliente

###
POST http://localhost:3000/api/cliente
Content-Type: application/json

{
    "nome":"tohods",
    "cpf":"999.777.55555",
    "contato": "99999-9999",
    "endereco":"rua ola"
    
}

###
DELETE http://localhost:3000/api/cliente/2


###

PATCH  http://localhost:3000/api/cliente/2
Content-Type: application/json

{
   "nome": "felipe",
    "cpf":"999.999.999-99",
    "contato": "99999-9999",
    "endereco":"rua seilt"
}
