@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzc5MzE0NDk2LCJleHAiOjE3NzkzNDMyOTZ9.PL-c0qD1p8P_ARbndESzb-SgYCthM8bXotVWo_VosCI

GET http://localhost:3000/api/cliente
Authorization: Bearer {{token}}

###
POST http://localhost:3000/api/cliente
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nome":"tohods",
    "cpf":"999.777.55555",
    "contato": "99999-9999",
    "endereco":"rua ola"
    
}

###
DELETE http://localhost:3000/api/cliente/1
Authorization: Bearer {{token}}


###

PATCH  http://localhost:3000/api/cliente/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "nome": "felipe",
    "cpf":"999.999.999-99",
    "contato": "99999-9999",
    "endereco":"rua seilt"
}
