//admin
//@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzc5MzE0NDk2LCJleHAiOjE3NzkzNDMyOTZ9.PL-c0qD1p8P_ARbndESzb-SgYCthM8bXotVWo_VosCI

//fun
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6ImZ1bmNpb25hcmlvIiwiaWF0IjoxNzc5MzE0NzczLCJleHAiOjE3NzkzNDM1NzN9.zZRpP_2WN_zTy2LeSedNMYIlHeVMSPT3hHKOekqIi9Q

GET http://localhost:3000/api/locacoes
Authorization: Bearer {{token}}


###

POST http://localhost:3000/api/locacoes
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "dataLocacao":"2026-05-10",
    "dataDevolucaoPrevista":"2026-05-17",
    "produtos": {
        "id": 4
    },
    "cliente":{
        "id":2
    }
}


###

PATCH  http://localhost:3000/api/locacoes/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    
    "dataDevolucaoReal": "2026-05-19"
     
}