GET http://localhost:3000/api/user

###
POST http://localhost:3000/api/user
Content-Type: application/json

{
    "name":"Alan",
    "cpf":"999.999.00000",
    "contato": "99999-9999",
    "endereco":"rua ola"
    
}

###
DELETE http://localhost:3000/api/user/99999


###

PATCH  http://localhost:3000/api/user/2
Content-Type: application/json

{
   "name": " Bruno",
    "cpf":"999.999.999-99",
    "contato": "99999-9999",
    "endereco":"rua seilt"
}
