@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwicm9sZSI6ImZ1bmNpb25hcmlvIiwiaWF0IjoxNzc5MjM1NTQ0LCJleHAiOjE3NzkyNjQzNDR9.ZEBGJssmOqrejz0fG-xrvY-U5MruQZRuM3e-vBDhSGA

### Listar usuarios
GET http://localhost:3000/api/user
Authorization: Bearer {{token}}

###
POST http://localhost:3000/api/user
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "edbabab5",
    "cpf":"999.999.00000",
    "contato": "99999-9999",
    "endereco":"rua ola"
}

###
DELETE http://localhost:3000/api/user/2
Authorization: Bearer {{token}}

###
PATCH http://localhost:3000/api/user/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "name": "lucas",
    "cpf":"999.999.999-99",
    "contato": "99999-9999",
    "endereco":"rua seilt"
}